name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
    - name: rustfmt
      uses: mbrobbel/rustfmt-check@0.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: clippy
      uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
