name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
          components: clippy, rustfmt
    - name: clippy
      uses: clechasseur/rs-clippy-check@v3
    - name: rustfmt
      uses: mbrobbel/rustfmt-check@0.8.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        mode: review
